import { Component, inject, input, signal } from '@angular/core';
import { I18n } from '../../core/i18n/i18n.service';
import { RemindersStore } from './reminders.store';
import type { Medication } from './medications.logic';
import {
  ALL_CHANNELS,
  ReminderChannel,
  ReminderPreferences,
  minutesToClock,
  clockToMinutes,
  describeQuietHours,
  smsVoiceStatus,
} from './reminders.logic';

/** IANA zone suggestions for the datalist (values are not localized). */
const TIMEZONES = ['Europe/Athens', 'Europe/London', 'Europe/Berlin', 'America/New_York', 'UTC'];

/**
 * Per-reminder channel preferences (FEATURE_PLAN.md §8 subtask 2): the
 * channel checkboxes, the "next reminder … via …" preview (subtask 6) and
 * the "send test reminder now" button (subtask 9) for one medication.
 * A11y: real fieldset/legend + labelled checkboxes; the preview is a
 * `role="status"` live region.
 *
 * Bilingual. The preview text is generated by `RemindersStore.previewFor`,
 * which takes the active locale.
 */
@Component({
  selector: 'app-reminder-channel-prefs',
  standalone: true,
  imports: [],
  template: `
    @if (medication(); as med) {
      <fieldset class="channel-prefs">
        <legend>{{ i18n.t('reminders.channelsFor', { name: med.name }) }}</legend>
        <div class="channels">
          @for (channel of channels; track channel) {
            <label [attr.for]="boxId(med.id, channel)">
              <input
                type="checkbox"
                [attr.id]="boxId(med.id, channel)"
                [checked]="store.channelsFor(med.id).includes(channel)"
                [attr.aria-describedby]="helpId(med.id, channel)"
                (change)="toggle(med, channel, $event)"
              />
              {{ channelLabel(channel) }}
            </label>
            <p class="help" [attr.id]="helpId(med.id, channel)">{{ channelHelp(channel) }}</p>
          }
        </div>
        <p class="preview" role="status">{{ previewFor(med) }}</p>
        <button
          type="button"
          class="btn test-btn"
          [attr.aria-label]="i18n.t('reminders.sendTestFor', { name: med.name })"
          (click)="store.sendTestReminder(med)"
        >
          {{ i18n.t('reminders.sendTest') }}
        </button>
      </fieldset>
    }
  `,
  styles: `
    .channel-prefs {
      border: 1px solid var(--border);
      border-radius: var(--radius-md);
      padding: var(--space-3);
      margin-top: var(--space-3);
    }
    .channels {
      display: grid;
      gap: 0.15rem;
    }
    .channels label {
      display: flex;
      align-items: center;
      gap: var(--space-2);
      min-height: 44px;
      font-weight: var(--weight-semibold);
    }
    .channels input[type='checkbox'] {
      width: auto;
    }
    .help {
      margin: 0 0 0.25rem 1.6rem;
      color: var(--text-muted);
      font-size: var(--text-sm);
    }
    .preview {
      margin: var(--space-2) 0;
      color: var(--text-muted);
    }
    .test-btn {
      min-height: 44px;
    }
  `,
})
export class ReminderChannelPrefsComponent {
  readonly store = inject(RemindersStore);
  protected readonly i18n = inject(I18n);
  readonly medication = input<Medication | null>(null);

  protected readonly channels = ALL_CHANNELS;

  /** "next reminder … via …" in the active language (subtask 6). */
  protected previewFor(med: Medication): string {
    return this.store.previewFor(med, Date.now(), this.i18n.language());
  }

  protected channelLabel(channel: ReminderChannel): string {
    return this.i18n.t(`reminders.channel.${channel}`);
  }

  protected channelHelp(channel: ReminderChannel): string {
    return this.i18n.t(`reminders.channelHelp.${channel}`);
  }

  boxId(medId: string, channel: ReminderChannel): string {
    return `reminder-ch-${medId}-${channel}`;
  }

  helpId(medId: string, channel: ReminderChannel): string {
    return `reminder-ch-${medId}-${channel}-help`;
  }

  toggle(med: Medication, channel: ReminderChannel, event: Event): void {
    const checked = (event.target as HTMLInputElement).checked;
    const current = this.store.channelsFor(med.id);
    const next = checked ? [...current, channel] : current.filter((c) => c !== channel);
    this.store.setChannels(med.id, next).subscribe();
  }
}

/**
 * Global reminder settings (FEATURE_PLAN.md §8 subtasks 5, 7, 10, 12, 14,
 * 15, 19): quiet hours, IANA timezone, SMS/voice phone + pending/configured
 * states, GDPR consent capture, caregiver duplicate opt-in, browser-push
 * opt-in, and the sent/failed history log. Usable inline and as the
 * `/reminders` route component.
 *
 * Bilingual. Form control ids and `aria-describedby` wiring are load-bearing
 * for the a11y checks and are kept stable.
 */
@Component({
  selector: 'app-reminder-settings',
  standalone: true,
  imports: [],
  template: `
    <section class="reminder-settings" aria-labelledby="reminder-settings-title">
      <h2 id="reminder-settings-title">{{ i18n.t('reminders.title') }}</h2>
      @if (store.error()) {
        <p class="error" role="alert">{{ i18n.message(store.errorSource(), store.error()) }}</p>
      }

      <fieldset>
        <legend>{{ i18n.t('reminders.quietHours') }}</legend>
        <p class="help" id="quiet-help">
          {{ i18n.t('reminders.quietHelp', { summary: quietSummary() }) }}
        </p>
        <label for="quiet-enabled">
          <input
            id="quiet-enabled"
            type="checkbox"
            [checked]="store.prefs().quietHours !== null"
            aria-describedby="quiet-help"
            (change)="toggleQuiet($event)"
          />
          {{ i18n.t('reminders.quietEnable') }}
        </label>
        @if (store.prefs().quietHours; as quiet) {
          <div class="row">
            <label for="quiet-start">{{ i18n.t('reminders.startsAt') }}</label>
            <input
              id="quiet-start"
              type="time"
              [value]="clock(quiet.startMinutes)"
              (change)="setQuietBound('start', $event)"
            />
            <label for="quiet-end">{{ i18n.t('reminders.endsAt') }}</label>
            <input
              id="quiet-end"
              type="time"
              [value]="clock(quiet.endMinutes)"
              (change)="setQuietBound('end', $event)"
            />
          </div>
        }
      </fieldset>

      <div class="field">
        <label class="field-label" for="reminder-tz">{{ i18n.t('reminders.timezone') }}</label>
        <input
          id="reminder-tz"
          type="text"
          list="reminder-tz-list"
          autocomplete="off"
          [value]="store.prefs().timezone"
          aria-describedby="reminder-tz-help reminder-tz-error"
          (change)="setTimezone($event)"
        />
        <datalist id="reminder-tz-list">
          @for (tz of timezones; track tz) {
            <option [value]="tz"></option>
          }
        </datalist>
        <p class="help" id="reminder-tz-help">{{ i18n.t('reminders.timezoneHelp') }}</p>
        @if (tzError()) {
          <p class="error" role="alert" id="reminder-tz-error">{{ tzError() }}</p>
        }
      </div>

      <fieldset>
        <legend>{{ i18n.t('reminders.smsVoice') }}</legend>
        <p class="help" id="telephony-help">
          {{
            i18n.t('reminders.telephonyHelp', {
              sms: stateLabel(telephony().sms),
              voice: stateLabel(telephony().voice)
            })
          }}
        </p>
        <div class="field">
          <label class="field-label" for="reminder-phone">{{ i18n.t('reminders.phone') }}</label>
          <input
            id="reminder-phone"
            type="tel"
            autocomplete="tel"
            [value]="store.prefs().phone"
            aria-describedby="telephony-help"
            (change)="setPhone($event)"
          />
        </div>
        <label for="consent-sms">
          <input
            id="consent-sms"
            type="checkbox"
            [checked]="store.prefs().consents.sms"
            aria-describedby="consent-help"
            (change)="setConsent('sms', $event)"
          />
          {{ i18n.t('reminders.consentSms') }}
        </label>
        <label for="consent-voice">
          <input
            id="consent-voice"
            type="checkbox"
            [checked]="store.prefs().consents.voice"
            aria-describedby="consent-help"
            (change)="setConsent('voice', $event)"
          />
          {{ i18n.t('reminders.consentVoice') }}
        </label>
        <p class="help" id="consent-help">{{ i18n.t('reminders.consentHelp') }}</p>
      </fieldset>

      <fieldset>
        <legend>{{ i18n.t('reminders.familyCopy') }}</legend>
        <label for="caregiver-copy">
          <input
            id="caregiver-copy"
            type="checkbox"
            [checked]="store.prefs().caregiverCopy.enabled"
            aria-describedby="caregiver-copy-help"
            (change)="setCaregiverCopyEnabled($event)"
          />
          {{ i18n.t('reminders.caregiverCopy') }}
        </label>
        <p class="help" id="caregiver-copy-help">{{ i18n.t('reminders.caregiverHelp') }}</p>
        @if (store.prefs().caregiverCopy.enabled) {
          <div class="field">
            <label class="field-label" for="caregiver-rel">{{ i18n.t('reminders.relationship') }}</label>
            <input
              id="caregiver-rel"
              type="text"
              [attr.placeholder]="i18n.t('reminders.relationshipPlaceholder')"
              [value]="store.prefs().caregiverCopy.relationship"
              (change)="setCaregiverRelationship($event)"
            />
          </div>
        }
      </fieldset>

      <div class="field push">
        <!-- The visible label stays the accessible name (WCAG 2.5.3); the
             current state is announced by the push-help description. -->
        <button type="button" class="btn secondary" (click)="enablePush()" aria-describedby="push-help">
          {{ i18n.t('reminders.enablePush') }}
        </button>
        <p class="help" id="push-help">
          {{ i18n.t('reminders.pushState', { state: pushLabel() }) }}
        </p>
      </div>

      <section aria-labelledby="reminder-history-title">
        <h3 id="reminder-history-title">{{ i18n.t('reminders.history') }}</h3>
        @if (store.history().length === 0) {
          <p class="help">{{ i18n.t('reminders.historyEmpty') }}</p>
        } @else {
          <ol class="history" [attr.aria-label]="i18n.t('reminders.historyAria')">
            @for (entry of store.history().slice(0, 20); track entry.id) {
              <li>
                <strong>{{ entry.medicationName }}</strong>
                <span>
                  {{ i18n.t('reminders.historyVia', { channel: entry.channel, status: entry.status }) }}
                </span>
                <span class="help">{{ when(entry.atMs) }} · {{ entry.detail }}</span>
              </li>
            }
          </ol>
        }
      </section>
    </section>
  `,
  styles: `
    .reminder-settings {
      border-top: 2px solid var(--border);
      margin-top: var(--space-5);
      padding-top: var(--space-3);
      display: grid;
      gap: var(--space-4);
    }
    fieldset {
      border: 1px solid var(--border);
      border-radius: var(--radius-md);
      padding: var(--space-3);
    }
    legend {
      font-weight: var(--weight-bold);
      padding: 0 0.3rem;
    }
    .field {
      display: grid;
      gap: 0.3rem;
    }
    .row {
      display: flex;
      align-items: center;
      gap: var(--space-2);
      flex-wrap: wrap;
      margin-top: var(--space-2);
    }
    label {
      display: flex;
      align-items: center;
      gap: var(--space-2);
      min-height: 44px;
    }
    label input[type='checkbox'] {
      width: auto;
    }
    .field .field-label {
      font-weight: var(--weight-semibold);
      color: var(--text-muted);
      font-size: var(--text-sm);
    }
    input[type='text'],
    input[type='tel'],
    input[type='time'] {
      min-height: 44px;
    }
    .push button {
      justify-self: start;
    }
    .help {
      margin: 0.15rem 0;
      color: var(--text-muted);
      font-size: var(--text-sm);
    }
    .error {
      color: var(--danger);
      font-weight: var(--weight-semibold);
    }
    .history {
      margin: var(--space-2) 0;
      padding-left: 1.2rem;
      display: grid;
      gap: var(--space-2);
    }
    .history li {
      display: grid;
      gap: 0.1rem;
    }
  `,
})
export class ReminderSettingsComponent {
  readonly store = inject(RemindersStore);
  protected readonly i18n = inject(I18n);
  protected readonly timezones = TIMEZONES;
  protected readonly tzError = signal('');

  constructor() {
    this.store.load().subscribe();
  }

  /** "off" or a HH:MM–HH:MM range (times are locale-neutral). */
  quietSummary(): string {
    const quiet = this.store.prefs().quietHours;
    return quiet ? describeQuietHours(quiet) : this.i18n.t('reminders.quietOff');
  }

  telephony(): { sms: string; voice: string } {
    return smsVoiceStatus(this.store.prefs());
  }

  /** `configured` / `pending` from the logic layer → localized label. */
  stateLabel(state: string): string {
    return this.i18n.t(`reminders.telephony.${state}`);
  }

  pushLabel(): string {
    const state = this.store.pushState();
    if (state === 'granted' || this.store.prefs().pushEnabled) {
      return this.i18n.t('reminders.push.enabled');
    }
    if (state === 'denied') {
      return this.i18n.t('reminders.push.blocked');
    }
    if (state === 'unsupported') {
      return this.i18n.t('reminders.push.unsupported');
    }
    return this.i18n.t('reminders.push.disabled');
  }

  clock(minutes: number): string {
    return minutesToClock(minutes);
  }

  when(atMs: number): string {
    try {
      return new Date(atMs).toLocaleString(this.i18n.locale());
    } catch {
      return '';
    }
  }

  toggleQuiet(event: Event): void {
    const enabled = (event.target as HTMLInputElement).checked;
    const fallback: ReminderPreferences['quietHours'] = { startMinutes: 22 * 60, endMinutes: 7 * 60 };
    this.store.setQuietHours(enabled ? (this.store.prefs().quietHours ?? fallback) : null).subscribe();
  }

  setQuietBound(which: 'start' | 'end', event: Event): void {
    const minutes = clockToMinutes((event.target as HTMLInputElement).value);
    if (minutes === null) {
      return;
    }
    const current = this.store.prefs().quietHours ?? { startMinutes: 22 * 60, endMinutes: 7 * 60 };
    this.store
      .setQuietHours(
        which === 'start'
          ? { ...current, startMinutes: minutes }
          : { ...current, endMinutes: minutes }
      )
      .subscribe();
  }

  setTimezone(event: Event): void {
    const value = (event.target as HTMLInputElement).value.trim();
    this.tzError.set('');
    this.store.setTimezone(value).subscribe((ok) => {
      if (!ok) {
        this.tzError.set(this.i18n.t('reminders.timezoneUnknown', { value }));
      }
    });
  }

  setPhone(event: Event): void {
    this.store.setPhone((event.target as HTMLInputElement).value).subscribe();
  }

  setConsent(kind: 'sms' | 'voice', event: Event): void {
    this.store.setConsent(kind, (event.target as HTMLInputElement).checked).subscribe();
  }

  setCaregiverCopyEnabled(event: Event): void {
    const prefs = this.store.prefs();
    this.store
      .setCaregiverCopy({ ...prefs.caregiverCopy, enabled: (event.target as HTMLInputElement).checked })
      .subscribe();
  }

  setCaregiverRelationship(event: Event): void {
    const prefs = this.store.prefs();
    this.store
      .setCaregiverCopy({ ...prefs.caregiverCopy, relationship: (event.target as HTMLInputElement).value })
      .subscribe();
  }

  async enablePush(): Promise<void> {
    await this.store.requestPush();
  }
}
